/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * Toptal Calories Tracker App
 * The Toptal Calories Tracker App API description
 * OpenAPI spec version: 1.0
 */

export interface FoodEntrySerializer {
  id: number;
  food_name: string;
  taken_at: string;
  calories_count: string;
}
