import {MigrationInterface, QueryRunner} from "typeorm";

export class init1643464093902 implements MigrationInterface {
    name = 'init1643464093902'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TYPE "public"."user_role_enum" AS ENUM('user', 'admin', 'super_admin')
        `);
        await queryRunner.query(`
            CREATE TABLE "user" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "first_name" character varying(30),
                "last_name" character varying(30),
                "email" character varying(30) NOT NULL,
                "hashed_password" text NOT NULL,
                "user_calories_limit" numeric NOT NULL DEFAULT '2100',
                "user_monthly_spend_limit" numeric NOT NULL DEFAULT '1000',
                "role" "public"."user_role_enum" NOT NULL DEFAULT 'user',
                CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE TABLE "food_entry" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "food_name" text NOT NULL,
                "taken_at" TIMESTAMP WITH TIME ZONE NOT NULL,
                "calories_count" numeric NOT NULL,
                "user_id" integer NOT NULL,
                CONSTRAINT "PK_8fb8473c98ef0a33c9b3a64f498" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            ALTER TABLE "food_entry"
            ADD CONSTRAINT "FK_796e7857a59eeacb2a0f25c9d4b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "food_entry" DROP CONSTRAINT "FK_796e7857a59eeacb2a0f25c9d4b"
        `);
        await queryRunner.query(`
            DROP TABLE "food_entry"
        `);
        await queryRunner.query(`
            DROP TABLE "user"
        `);
        await queryRunner.query(`
            DROP TYPE "public"."user_role_enum"
        `);
    }

}
